collision_monitor:
  ros__parameters:
    observation_sources: laser_scan
    laser_scan.topic: /scan
    laser_scan.max_obstacle_height: 0.5
    laser_scan.min_obstacle_height: 0.0
    laser_scan.obstacle_range: 2.5
    laser_scan.expected_update_rate: 10.0
    laser_scan.buffer_size: 1
