ekf_filter_node:
  ros__parameters:
    ########################
    # Core timing / TF
    ########################
    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    predict_to_current_time: true
    transform_time_offset: 0.0
    transform_timeout: 0.5
    print_diagnostics: true
    debug: false
    debug_out_file: ""

    publish_tf: true
    permit_corrected_publication: false
    publish_acceleration: false
    smooth_lagged_data: false
    reset_on_time_jump: true

    ########################
    # Frames
    ########################
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom   # AMCL จะทำ map->odom แยก

    ########################
    # ODOM (from merge_odom.py)
    ########################
    odom0: odom/raw
    # layout:  [x, y, z, roll, pitch, yaw,
    #           vx, vy, vz, vroll, vpitch, vyaw,
    #           ax, ay, az]
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: true
    odom0_relative: false
    odom0_pose_rejection_threshold: 5.0
    odom0_twist_rejection_threshold: 1.0

    ########################
    # IMU (orientation yaw only)
    ########################
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_queue_size: 10
    imu0_nodelay: true
    imu0_differential: false
    imu0_relative: false
    imu0_pose_rejection_threshold: 2.0
    imu0_twist_rejection_threshold: 2.0
    imu0_linear_acceleration_rejection_threshold: 2.0
    imu0_remove_gravitational_acceleration: true

    ########################
    # Process noise (Q) — ใช้ float ล้วน
    ########################
    # ลำดับสถานะ (15): x y z roll pitch yaw vx vy vz vroll vpitch vyaw ax ay az
    process_noise_covariance: [
      1.0e-2, 0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,
      0.0,    1.0e-2,  0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,
      0.0,    0.0,     1.0e3,   0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,

      0.0,    0.0,     0.0,     1.0e3,   0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,
      0.0,    0.0,     0.0,     0.0,     1.0e3,   0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,
      0.0,    0.0,     0.0,     0.0,     0.0,     1.0e-4,  0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,   # yaw

      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     5.0e-3,  0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,   # vx
      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     5.0e-3,  0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,   # vy
      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0e3,   0.0,     0.0,     0.0,     0.0,     0.0,     0.0,

      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0e3,   0.0,     0.0,     0.0,     0.0,     0.0,
      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0e3,   0.0,     0.0,     0.0,     0.0,
      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0e-3,  0.0,     0.0,     0.0,   # vyaw

      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0e-1,  0.0,     0.0,
      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0e-1,  0.0,
      0.0,    0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0e2
    ]

    ########################
    # Initial estimate covariance (P0) — ใช้ float ล้วน
    ########################
    initial_estimate_covariance: [
      1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  1.0e6,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,

      0.0,  0.0,  0.0,  1.0e6,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  1.0e6,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  3.0e-1,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  # yaw เริ่มไม่แน่น

      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  5.0e-1,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  5.0e-1,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0e6,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,

      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0e6,0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0e6,0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  5.0e-1,0.0,  0.0,  0.0,

      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0e1
    ]
