amcl:
  ros__parameters:
    use_sim_time: false
    # เพิ่มความแม่นยำในการประมาณการเคลื่อนที่
    alpha1: 0.1  # ลดลงเพื่อความแม่นยำในการเคลื่อนที่ตรง
    alpha2: 0.1  # ลดลงเพื่อความแม่นยำในการหมุน
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1
    base_frame_id: "base_link"
    
    # เพิ่มประสิทธิภาพการใช้ laser
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.95
    beam_skip_threshold: 0.35
    do_beamskip: true  # เปิดใช้งานเพื่อกรอง noise
    laser_likelihood_max_dist: 2.0
    laser_max_range: 3.0
    laser_min_range: 0.25
    laser_model_type: "likelihood_field"
    max_beams: 100  # เพิ่มจำนวน beams เพื่อความแม่นยำ
    
    # ปรับ particle filter
    max_particles: 5000  # ลดลงเพื่อการประมวลผลที่เร็วขึ้น
    min_particles: 1000
    pf_err: 0.01
    pf_z: 0.99
    
    # ปิดการ recovery เพื่อป้องกันการกระโดดตำแหน่ง
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    
    # เพิ่มความถี่ในการอัพเดท
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # เปลี่ยนเป็น differential drive
    save_pose_rate: 20.0  # เพิ่มความถี่การบันทึกตำแหน่ง
    
    # ปรับความแม่นยำของ laser
    sigma_hit: 0.02
    transform_tolerance: 0.05  # ลดลงเพื่อการอัพเดทที่เร็วขึ้น
    
    # เพิ่มความถี่การอัพเดท
    update_min_a: 0.01  # ลดลงเพื่ออัพเดทบ่อยขึ้นเมื่อหมุน
    update_min_d: 0.01  # ลดลงเพื่ออัพเดทบ่อยขึ้นเมื่อเคลื่อนที่
    
    # ปรับการให้น้ำหนักกับการวัด
    z_hit: 0.85  # เพิ่มน้ำหนักการวัดที่ตรงกับ map
    z_max: 0.05
    z_rand: 0.1  # ลดลงมากเพื่อลดผลกระทบของ noise
    z_short: 0.05
    
    scan_topic: "filtered_scan"
    first_map_only: true  # เปิดใช้งานเพื่อความเสถียร
    global_localization: false

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 50.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.1
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.25
      movement_time_allowance: 10.0
    
    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      theta_stopped_velocity: 0.25

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.8
      transform_tolerance: 1.0
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.05
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 4.0
      max_robot_pose_search_dist: 10.0
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: false
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      robot_radius: 0.22
      transform_tolerance: 1.0
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /filtered_scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.2
          obstacle_max_range: 4.5
          obstacle_min_range: 0.2
      always_send_full_costmap: true
  local_costmap_client:
    ros__parameters:
      use_sim_time: false
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      robot_radius: 0.22
      resolution: 0.05
      transform_tolerance: 1.0
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /filtered_scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.2
          obstacle_max_range: 4.5
          obstacle_min_range: 0.2
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        transform_tolerance: 1.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: true

  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.2
      use_astar: true
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
      max_rotational_vel: 1.0
      min_rotational_vel: 0.3
      rotational_acc_lim: 3.2
    backup:
      plugin: "nav2_recoveries/BackUp"
      speed: 0.1
      acceleration: 0.2
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 2000
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 50.0
    scale_velocities: true
    feedback: "OPEN_LOOP"
    max_velocity: [0.4, 0.0, 0.6]
    min_velocity: [-0.4, -0.0, -0.6]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    max_accel: [2.5, 0.0, 4.0]
    max_decel: [-2.5, -0.0, -4.0]
    odom_topic: "odom"
    odom_duration: 0.1
    use_realtime_priority: true
    enable_stamped_cmd_vel: false

# smoother_server:
#   ros__parameters:
#     costmap_topic: global_costmap/costmap_raw
#     footprint_topic: global_costmap/published_footprint
#     robot_base_frame: base_link
#     transform_timeout: 0.1
#     smoother_plugins: ["SmoothPath"]
#     SmoothPath:
#       plugin: "nav2_constrained_smoother/ConstrainedSmoother"
#       reversing_enabled: true
#       path_downsampling_factor: 5
#       path_upsampling_factor: 2
#       keep_start_orientation: true
#       keep_goal_orientation: true
#       minimum_turning_radius: 0.1
#       w_curve: 20.0
#       w_dist: 0.02
#       w_smooth: 400000000.0
#       w_cost: 0.05
#       w_cost_cusp_multiplier: 3.0