amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.05  # Reduced for faster updates
    alpha2: 0.05  # Reduced for faster updates
    alpha3: 0.2   # Increased for faster motion
    alpha4: 0.2   # Increased for faster motion
    alpha5: 0.05  # Reduced for faster updates
    base_frame_id: "base_link"
    beam_skip_distance: 0.2  # Reduced for narrow map
    beam_skip_error_threshold: 0.5
    beam_skip_threshold: 0.3
    do_beamskip: true
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 1.0  # Reduced for narrow map
    laser_max_range: 5.0  # Reduced for narrow map
    laser_min_range: 0.05
    laser_model_type: "likelihood_field"
    max_beams: 60  # Reduced for faster processing
    max_particles: 5000  # Reduced for faster processing
    min_particles: 1200   # Reduced for faster processing
    odom_frame_id: "odom"
    pf_err: 0.01  # Reduced for better tracking
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 5.0
    sigma_hit: 0.05
    tf_broadcast: true
    transform_tolerance: 0.5  # Reduced for faster updates
    update_min_a: 0.0001  # Increased for faster updates
    update_min_d: 0.0001  # Increased for faster updates
    z_hit: 0.9
    z_max: 0.05
    z_rand: 0.05
    z_short: 0.05
    scan_topic: "scan"
    first_map_only: false
    global_localization: false

amcl_map_client:
  ros__parameters:
    use_sim_time: false

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false


bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    error_code_names: [compute_path_error_code, follow_path_error_code]

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.4
      movement_time_allowance: 10.0

    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.04
      yaw_goal_tolerance: 0.035

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

      motion_model: "Omni"
      time_steps: 50
      model_dt: 0.05
      batch_size: 2400

      # เพิ่มความเร็วตรง + ลดความเร็วหมุนลง 10%
      vx_max: 0.22       # เดิม 0.18
      vx_min: -0.10
      vy_max: 0.22       # เดิม 0.18
      vy_min: -0.22
      wz_max: 0.45       # เดิม 0.55 → ลด ~10%

      # Noise ให้บาลานซ์กับความเร็วใหม่
      vx_std: 0.07
      vy_std: 0.07
      wz_std: 0.08

      temperature: 0.23
      gamma: 0.02
      iteration_count: 1
      prune_distance: 0.6
      regenerate_noises: false
      visualize: false

      critics:
        - "ConstraintCritic"
        - "CostCritic"
        - "GoalCritic"
        - "GoalAngleCritic"
        - "PathAlignCritic"
        - "PathFollowCritic"
        - "PreferForwardCritic"

      ConstraintCritic:
        enabled: true
        cost_weight: 6.0

      CostCritic:
        enabled: true
        consider_footprint: false
        cost_weight: 9.0
        cost_power: 1
        collision_cost: 1000000.0
        critical_cost: 200.0
        near_goal_distance: 0.4
        trajectory_point_step: 2

      PathAlignCritic:
        enabled: true
        cost_weight: 18.0
        threshold_to_consider: 0.8
        offset_from_furthest: 18
        use_path_orientations: false
        trajectory_point_step: 4

      PathFollowCritic:
        enabled: true
        cost_weight: 9.0
        threshold_to_consider: 1.0
        offset_from_furthest: 6

      GoalCritic:
        enabled: true
        cost_weight: 6.0
        threshold_to_consider: 1.0

      GoalAngleCritic:
        enabled: true
        cost_weight: 6.0
        threshold_to_consider: 1.0

      PreferForwardCritic:
        enabled: true
        cost_weight: 4.0
        threshold_to_consider: 0.6

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 12.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 1
      height: 1
      resolution: 0.015
      robot_radius: 0.105
      footprint_padding: 0.0
      # ใช้ ObstacleLayer + InflationLayer (ตัด VoxelLayer ออกให้เรียบง่าย)
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 2.5
          raytrace_min_range: 0.0
          obstacle_max_range: 2.0
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 11.0
        inflation_radius: 0.042       # ช่อง 30 ซม.: 0.045 = margin ~5 ซม./ด้าน

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      always_send_full_costmap: true

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 8.0
      publish_frequency: 8.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.105
      resolution: 0.03
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      # ให้ planner เห็นทางแคบได้ แต่ไม่บีบเกินไป
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.5
        inflation_radius: 0.055

      always_send_full_costmap: true

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 1.0
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

behavior_server:
  ros__parameters:
    use_sim_time: false
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.20, 0.20, 1.40]   # z สูงพอให้ถึง wz_max 0.55 แบบมีเฮดรูม
    min_velocity: [-0.12, -0.20, -1.40]
    max_accel: [1.2, 1.2, 3.0]
    max_decel: [-1.2, -1.2, -3.0]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: true
    stop_pub_timeout: 2.0
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 0.9      # ตื่นตัวขึ้นสำหรับซอก
      simulation_time_step: 0.1
      min_points: 6
      visualize: false
      enabled: true
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.0
      max_height: 2.0
      enabled: false

docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false
      use_stall_detection: false
      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0
      simulation_step: 0.1
      dock_collision_threshold: 0.3

loopback_simulator:
  ros__parameters:
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    map_frame_id: "map"
    scan_frame_id: "laser"
    update_duration: 0.02
